#!/usr/bin/env python
import rospy
import rosxslt
import argparse
import sys

if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser()
        parser.description = "XSLT Macro wrapper for ROS Industrial"
        parser.prog = 'rosxslt'

        parser.add_argument('-o','--output', help = 'Output file path', default = sys.stdout, type=argparse.FileType('w'))
        parser.add_argument('input', nargs=1, help = 'File path to xslt macro.', type=argparse.FileType('r'))
        parser.add_argument('param', nargs='*', help = 'Parameters to xslt macro', type=str)
        arguments = parser.parse_args()
        rosxslt.main(arguments)
    except rospy.ROSInterruptException:
        pass
