#!/usr/bin/env python
import rospy
import argparse
import sys
import lxml.etree as macro
import rospkg



if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser()
        parser.description = "Converts xacro to xslt"
        parser.prog = 'xacro2xslt'
        parser.add_argument('input', nargs=1, help = 'File path to xacro to be converted.', type=argparse.FileType('r'))
        parser.add_argument('output', nargs='?', help = 'Output file path', default = [sys.stdout], type=argparse.FileType('w'))
        arguments = parser.parse_args()
        args = arguments

        #xacro2xslt.main(arguments)
        rospack = rospkg.RosPack()
        dom = macro.parse(args.input[0])
        conv_path = rospack.get_path("rosxslt") + "/include/rosxslt/converter.xsl"
        xslt = macro.parse(conv_path)
        transform = macro.XSLT(xslt)
        new_dom = transform(dom)
        args.output[0].write(macro.tostring(new_dom, pretty_print=True))
        args.input[0].close()
        args.output[0].close()

    except rospy.ROSInterruptException:
        pass
